{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.postgresPassword | default "changeme" | quote }}
  admin-password: {{ .Values.postgresql.adminPassword | default "changeme" | quote }}
  odoo-password: {{ .Values.databases.odoo.password | default "changeme" | quote }}
  n8n-password: {{ .Values.databases.n8n.password | default "changeme" | quote }}
  grafana-password: {{ .Values.databases.grafana.password | default "changeme" | quote }}
{{- end }}
